name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

deploy:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}

  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Publish to GitHub Pages 🚀
      id: deployment
      uses: actions/deploy-pages@v4
